#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S4_C1_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     LiftLow,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     FlagSpinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     LiftHigh,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     BlockBristles, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C4_2,     FrontRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

/*void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}*/


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  while (true)
{

    int Y1 = joystick.joy1_y1;
    int X1 = joystick.joy1_x1;
    int X2 = joystick.joy1_x2;
if(abs(Y1) < 10)
	Y1 = 0;
if(abs(X1) < 10)
	X1 = 0;
if(abs(X2) < 10)
	X2 = 0;


if(joy1Btn(6)) // Slow Drive
{
	 motor[FrontLeft] = Y1 + X2 + X1;
   motor[FrontRight] = Y1 - X2 - X1;
   motor[BackLeft] = Y1 + X2 - X1;
   motor[BackRight] = Y1 - X2 + X1;
}
else //Normal Drive
{
	 motor[FrontLeft] = Y1 + X2 + X1;
   motor[FrontRight] = Y1 - X2 - X1;
   motor[BackLeft] = Y1 + X2 - X1;
   motor[BackRight] = Y1 - X2 + X1;
}


//motor[FrontLeft] = Y1;






}
}
